# Generated by Django 4.2 on 2023-04-22 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrepod', models.CharField(choices=[('NEWS', 'News'), ('COMEDY', 'Comedy'), ('EDUCATION', 'Education'), ('SPORTS', 'Sports'), ('MUSIC', 'Music'), ('TECHNOLOGY', 'Technology'), ('BUSINESS', 'Business'), ('TRUE_CRIME', 'True Crime'), ('LIFESTYLE', 'Lifestyle'), ('SCIENCE', 'Science'), ('HISTORY', 'History'), ('FICTION', 'Fiction'), ('ARTS', 'Arts'), ('RELIGION', 'Religion')], default='TECHNOLOGY', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='podcastDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podname', models.CharField(max_length=20, verbose_name='Podcast Name')),
                ('liked', models.BooleanField(default=False)),
                ('poddata', models.FileField(upload_to='Podcast Data')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.genre')),
                ('podcreator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
