# Generated by Django 4.2 on 2023-04-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_podcastdetails_dateuploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastdetails',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
    ]
