# Generated by Django 4.2 on 2023-04-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_language_podcastdetails_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastdetails',
            name='Views',
            field=models.IntegerField(default=0, null=True, verbose_name='Views'),
        ),
    ]
