# Generated by Django 4.2 on 2023-04-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_podcastdetails_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastdetails',
            name='Land',
        ),
        migrations.RemoveField(
            model_name='podcastdetails',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='podcastdetails',
            name='typeofPodcast',
        ),
        migrations.AddField(
            model_name='podcastdetails',
            name='genrepod',
            field=models.CharField(choices=[('NEWS', 'News'), ('COMEDY', 'Comedy'), ('EDUCATION', 'Education'), ('SPORTS', 'Sports'), ('MUSIC', 'Music'), ('TECHNOLOGY', 'Technology'), ('BUSINESS', 'Business'), ('TRUE_CRIME', 'True Crime'), ('LIFESTYLE', 'Lifestyle'), ('SCIENCE', 'Science'), ('HISTORY', 'History'), ('FICTION', 'Fiction'), ('ARTS', 'Arts'), ('RELIGION', 'Religion')], default='TECHNOLOGY', max_length=10),
        ),
        migrations.AddField(
            model_name='podcastdetails',
            name='lang',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('RU', 'Russian'), ('ZH', 'Chinese'), ('JA', 'Japanese'), ('KO', 'Korean'), ('AR', 'Arabic'), ('HI', 'Hindi'), ('BN', 'Bengali'), ('UR', 'Urdu'), ('FA', 'Persian')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='podcastdetails',
            name='type',
            field=models.CharField(choices=[('AUDIO', 'audio'), ('VIDEO', 'video')], default='AUDIO', max_length=10),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='typeofPod',
        ),
    ]
